### ISSUE TITLE
trade history

### ISSUE THREAD

**Issue by benjyz** [delta-exchange/python-rest-client#11]
trying to get history

```
    def trade_history(self):
        query = {
            'page_num' : 1,
            'page_size' : 100
        }
        response = self._request("GET","orders/history",query=query)
        return response.json()
```

gives 
`delta request error:  401 Client Error: Unauthorized for url: https://api.delta.exchange/orders/history?page_num=1&page_size=100
`

**Comment by bbc4468** [comment]
Check the request method in the rest client. For accessing private data, you need to send authentication headers. Calling request method with auth=True will attach auth headers.

https://github.com/delta-exchange/python-rest-client/blob/master/delta_rest_client/delta_rest_client.py#L35
