### ISSUE TITLE
dynamic calls return static data

### ISSUE THREAD

**Issue by benjyz** [delta-exchange/python-rest-client#14]
position call returns static data. kind of verbose, I think that could be queried separately by product_id.

`  {'user_id': ..., 'size': 1, 'entry_price': '3821.0', 'margin': '0.00002617', 'liquidation_price': '3490.0', 'bankruptcy_price': '3474.0', 'adl_level': 1,  'product': ...}`

**Comment by marif4444** [comment]
Can u send the api endpoint and params you are sending?

**Comment by bbc4468** [comment]
Wont be changing this in current version. Will remove this in V2. Just ignore the product data for now.
