### ISSUE TITLE
wallet balance

### ISSUE THREAD

**Issue by benjyz** [delta-exchange/python-rest-client#15]
client or docs out of date?

`delta request error:  401 Client Error: Unauthorized for url: https://api.delta.exchange/wallet/balances`

https://docs.delta.exchange/#delta-exchange-api-wallet

**Comment by marif4444** [comment]
You need to pass the authentication header for private endpoints. You are using api or python client?

**Comment by benjyz** [comment]
just using client as in this line. the other calls work
https://github.com/delta-exchange/python-rest-client/blob/master/delta_rest_client/delta_rest_client.py#L117

**Comment by benjyz** [comment]
also not sure how to retrieve asset id for given asset. would nice to add in client get_assets (?)

**Comment by benjyz** [comment]
i.e. see #16

**Comment by bbc4468** [comment]
The following api returns the list of assets
https://api.delta.exchange/assets

Will add get_assets in the rest client. In the meanwhile, you can directly use the following function

response = client.request("GET", "assets")
assets = response.json()

**Comment by bbc4468** [comment]
We made intentionally made "request" function public for such cases.

**Comment by benjyz** [comment]
ok, it makes sense to cover all available calls? a more fully developed client makes it easier for those using it.

**Comment by bbc4468** [comment]
Done. closing the issue now.
