### ISSUE TITLE
symbol summary

### ISSUE THREAD

**Issue by benjyz** [delta-exchange/python-rest-client#19]
* client doesn't have ticker yet , i.e. get_ticker uses orderbook
https://docs.delta.exchange/#get-24hr-ticker

* wrong symbol doesn't throw exception

**Comment by benjyz** [comment]
* would be good to be able to retrieve the underlying asset, to be able to calculate USD volume

**Comment by bbc4468** [comment]
@benjyz We have updated the client for using 24hrticker api and published version "0.1.8". You can bump up your version to start using it.
We have added "USD volume in 24hr ticker" to our backlog as discussed over telegram channel.

Closing this thread.
