### ISSUE TITLE
cancel order function

### ISSUE THREAD

**Issue by benjyz** [delta-exchange/python-rest-client#9]
for batch cancel I get an error

batch_cancel(product_id, orders)

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.delta.exchange/orders/batch
`

**Comment by bbc4468** [comment]
Can you share the exact response body?

**Comment by benjyz** [comment]
solved the issue. my problem occurred because open_orders returned all orders, including cancelled, not just the open ones

I think adding a cancel function can't hurt

**Comment by benjyz** [comment]
actually its here, but not 100% clear to me at first sight
https://docs.delta.exchange/#cancel-order
